example_name: "intersection"

centerline_waypoints:
  - [[0.0, -100.0], [0.0, 0.0], [0.0, 500.0]]    # Vertical lane
  - [[-100.0, 0.0], [0.0, 0.0], [500.0, 0.0]]    # Horizontal lane

num_vehicles: 2
multi_vehicle_states:
  - [1.0, -50.0, 1.5708, 5.0]  # [x, y, heading, speed] - pi/2 = 1.5708
  - [-35.0, 1.5, 0.0, 5.0]

vehicle_sizes:
  - [4.0, 2.0, 3.0]  # [length, width, wheelbase]
  - [4.0, 2.0, 3.0]

sv_predicted_decision_set:
  decision_switch_time: 1.0
  decisions:
    stage_1:
      - [{speed: 5.0, lane_id: 1}, {speed: 1.0, lane_id: 1}]
    stage_2:
      - [{speed: 5.0, lane_id: 1}, {speed: 1.0, lane_id: 1}]

sv_decisions:
  - [5.0, 5.0, 1.0]  # v_des_stage1, v_des_stage2, switch_time